lanes:
  top:
    world: world
    #Coordonnées de la toplane - //TODO ajuster les coordonnées quand on aura les bonnes avec la map
    min: [-100, 60, -250]
    max: [-20, 60, -170]

    pvp_windows:
      - { start_sec: 180, duration_sec: 120 }

  mid:
    world: world
    #Coordonnées de la midlane - //TODO ajuster les coordonnées quand on aura les bonnes avec la map
    min: [-20, 60, -250]
    max: [20, 60, -170]
    pvp_windows:
      - { start_sec: 180, duration_sec: 120 }

  bot:
    world: world
    #Coordonnées de la botlane - //TODO ajuster les coordonnées quand on aura les bonnes avec la map
    min: [20, 60, -250]
    max: [100, 60, -170]
    pvp_windows:
      - { start_sec: 180, duration_sec: 120 }

timers:
  # Temps en secondes avant le début des fenêtres de PvP (pour permettre aux joueurs de se préparer)
  game_start_delay_sec: 30
